import gql from 'graphql-tag';

const orderFragment = gql`
  fragment orderFragment on Order {
    _id
    invoiceDate
    isAutoGenerated
    destination {
      address {
        address1
        address2
        city
        state
        zip
      }
      instructions
    }
    costs {
      mealPrices {
        stripePlanId
        planName
        mealPrice
      }
      promos {
        stripeCouponId
        percentOff
        amountOff
      }
      discounts {
        description
        amountOff
        percentOff
        reason
        referredUserId
      }
      tax
      deliveryFee
    }
    deliveries {
      deliveryTime
      deliveryDate
      meals {
        mealId
        img
        name
        quantity
        choices
        restId
        restName
        stripePlanId
        planName
        taxRate
        tags
      }
      status
    }
    phone
    donationCount
    name
    stripeInvoiceId
  }
`

export {
  orderFragment,
}